### ISSUE TITLE
[Koin] No need for createdAtStart

### ISSUE THREAD

**Issue by mradzinski** [skydoves/TheMovies2#2]
I think you got it wrong. By default Koin will behave lazily, so no need to set `createdAtStart = false` on each definition you don't wanna create during startup. I've also noticed some definitions don't have this property set, so I wonder if you thought not setting it would imply eager instantiation...

For example, here's Koin `single` DSL method. Notice `createdAtStart`:
```
    inline fun <reified T> single(
            qualifier: Qualifier? = null,
            createdAtStart: Boolean = false,
            override: Boolean = false,
            noinline definition: Definition<T>
    ): BeanDefinition<T>
```

**Comment by skydoves** [comment]
@mradzinski 
Oh, I thought the Koin will behave instantly instead of lazily,
so I set `createdAtStart = false` on each definition.
Thank you for your nice issue!

**Comment by mradzinski** [comment]
Very welcome 😊
